In [38]:
import numpy as np

all_array = np.zeros(shape=(1,3), dtype=float)

test = np.array([[0,1,2], [3,4,5]])
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(a)
print(b)
print('\n')
print(all_array)
print(all_array.shape)
print(type(all_array))
print(test)
print(test.shape)
print(type(test))
print('\n')
print(np.concatenate((a, b), axis=0))

print(np.concatenate((all_array, test), axis=0))

all_array = np.concatenate((all_array, test), axis=0)
all_array = all_array[1:]
all_array

[[1 2]
 [3 4]]
[[5 6]]


[[0. 0. 0.]]
(1, 3)
<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]]
(2, 3)
<class 'numpy.ndarray'>


[[1 2]
 [3 4]
 [5 6]]
[[0. 0. 0.]
 [0. 1. 2.]
 [3. 4. 5.]]


array([[0., 1., 2.],
       [3., 4., 5.]])

In [49]:
labels = np.ndarray(shape=(0,))

len(labels)

0

In [46]:
sss = np.array([[1,2,3]])
len(sss)

1